### PR TITLE
Minor QoL improvements

### PR DESCRIPTION
**Pull request by ghost**
This PR modifies some small things that improve general QoL:
- Added Favicon
- Made _"logo"_ clickable, redirecting to root (search)

### CODE REVIEW

**Review by kbdharun — APPROVED** [review]
LGTM, Thanks for your contribution.

**Comment by mirkobrombin** [comment]
There is no favicon in the static folder :eyes:

**Comment by ghost** [comment]
I was linking the file with the wrong extension, fixed in 460f818!

**Comment by ghost** [comment]
Closing due to inactivity

**Pull request closed without merging**
